name: Lint and Build
on: 
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build
      - name: linting typescript
        if: always()
        run: npm run lint:ts
      - name: linting css
        if: always()
        run: npm run lint:scss 
      - name: deploying website
        if: always()
        run: npm run deploy 

